version: "3.9"
services:
  infracloud:
    ports:
      - "9393:9300"
    volumes:
      - /home/aayush/inputFile:/csvserver/inputdata
    environment:
      CSVSERVER_BORDER: Orange
    image: "docker.io/infracloudio/csvserver"